/* Generated by latin2js. */
var Composetab = {
    " ": {
        from: " i",
        to: "␣ı"
    },
    "!~": {
        from: "-=~",
        to: "≄≇≉"
    },
    "!": {
        from: "!<=>?bmp",
        to: "¡≮≠≯‽⊄∉⊅"
    },
    "\"*": {
        from: "IUiu",
        to: "ΪΫϊϋ"
    },
    "\"": {
        from: "\"AEIOUYaeiouy",
        to: "¨ÄËÏÖÜŸäëïöüÿ"
    },
    "$*": {
        from: "fhk",
        to: "ϕϑϰ"
    },
    "$": {
        from: "BEFHILMRVaefglopv",
        to: "ℬℰℱℋℐℒℳℛƲɑℯƒℊℓℴ℘ʋ"
    },
    "\'\"": {
        from: "Uu",
        to: "Ǘǘ"
    },
    "\'": {
        from: "\'ACEILNORSUYZacegilnorsuyz",
        to: "´ÁĆÉÍĹŃÓŔŚÚÝŹáćéģíĺńóŕśúýź"
    },
    "*": {
        from: "*ABCDEFGHIKLMNOPQRSTUWXYZabcdefghiklmnopqrstuwxyz",
        to: "∗ΑΒΞΔΕΦΓΘΙΚΛΜΝΟΠΨΡΣΤΥΩΧΗΖαβξδεφγθικλμνοπψρστυωχηζ"
    },
    "+": {
        from: "-O",
        to: "±⊕"
    },
    ",": {
        from: ",ACEGIKLNORSTUacegiklnorstu",
        to: "¸ĄÇĘĢĮĶĻŅǪŖŞŢŲąçęģįķļņǫŗşţų"
    },
    "-*": {
        from: "l",
        to: "ƛ"
    },
    "-": {
        from: "+-2:>DGHILOTZbdghiltuz~",
        to: "∓­ƻ÷→ÐǤĦƗŁ⊖ŦƵƀðǥℏɨłŧʉƶ≂"
    },
    ".": {
        from: ".CEGILOZceglz",
        to: "·ĊĖĠİĿ⊙Żċėġŀż"
    },
    "/": {
        from: "Oo",
        to: "Øø"
    },
    "1": {
        from: ".234568",
        to: "․½⅓¼⅕⅙⅛"
    },
    "2": {
        from: "-.35",
        to: "ƻ‥⅔⅖"
    },
    "3": {
        from: ".458",
        to: "…¾⅗⅜"
    },
    "4": {
        from: "5",
        to: "⅘"
    },
    "5": {
        from: "68",
        to: "⅚⅝"
    },
    "7": {
        from: "8",
        to: "⅞"
    },
    ":": {
        from: "()-=",
        to: "☹☺÷≔"
    },
    "<!": {
        from: "=~",
        to: "≨⋦"
    },
    "<": {
        from: "-<=>~",
        to: "←«≤≶≲"
    },
    "=": {
        from: ":<=>OV",
        to: "≕⋜≡⋝⊜⇒"
    },
    ">!": {
        from: "=~",
        to: "≩⋧"
    },
    ">": {
        from: "<=>~",
        to: "≷≥»≳"
    },
    "?": {
        from: "!?",
        to: "‽¿"
    },
    "@\'": {
        from: "\'",
        to: "ъ"
    },
    "@@": {
        from: "\'EKSTYZekstyz",
        to: "ьЕКСТЫЗекстыз"
    },
    "@C": {
        from: "Hh",
        to: "ЧЧ"
    },
    "@E": {
        from: "Hh",
        to: "ЭЭ"
    },
    "@K": {
        from: "Hh",
        to: "ХХ"
    },
    "@S": {
        from: "CHch",
        to: "ЩШЩШ"
    },
    "@T": {
        from: "Ss",
        to: "ЦЦ"
    },
    "@Y": {
        from: "AEOUaeou",
        to: "ЯЕЁЮЯЕЁЮ"
    },
    "@Z": {
        from: "Hh",
        to: "ЖЖ"
    },
    "@c": {
        from: "h",
        to: "ч"
    },
    "@e": {
        from: "h",
        to: "э"
    },
    "@k": {
        from: "h",
        to: "х"
    },
    "@s": {
        from: "ch",
        to: "щш"
    },
    "@t": {
        from: "s",
        to: "ц"
    },
    "@y": {
        from: "aeou",
        to: "яеёю"
    },
    "@z": {
        from: "h",
        to: "ж"
    },
    "@": {
        from: "ABDFGIJLMNOPRUVXabdfgijlmnopruvx",
        to: "АБДФГИЙЛМНОПРУВХабдфгийлмнопрувх"
    },
    "A": {
        from: "E",
        to: "Æ"
    },
    "C": {
        from: "ACU",
        to: "⋂ℂ⋃"
    },
    "Dv": {
        from: "Zz",
        to: "Ǆǅ"
    },
    "D": {
        from: "-e",
        to: "Ð∆"
    },
    "G": {
        from: "-",
        to: "Ǥ"
    },
    "H": {
        from: "-H",
        to: "Ħℍ"
    },
    "I": {
        from: "-J",
        to: "ƗĲ"
    },
    "L": {
        from: "&-Jj|",
        to: "⋀ŁǇǈ⋁"
    },
    "M": {
        from: "#48bs",
        to: "♮♩♪♭♯"
    },
    "N": {
        from: "JNj",
        to: "Ǌℕǋ"
    },
    "O": {
        from: "*+-./=EIcoprx",
        to: "⊛⊕⊖⊙⊘⊜ŒƢ©⊚℗®⊗"
    },
    "P": {
        from: "P",
        to: "ℙ"
    },
    "Q": {
        from: "Q",
        to: "ℚ"
    },
    "R": {
        from: "R",
        to: "ℝ"
    },
    "S": {
        from: "123S",
        to: "¹²³§"
    },
    "T": {
        from: "-u",
        to: "Ŧ⊨"
    },
    "V": {
        from: "=",
        to: "⇐"
    },
    "Y": {
        from: "R",
        to: "Ʀ"
    },
    "Z": {
        from: "-ACSZ",
        to: "Ƶℤ"
    },
    "^": {
        from: "ACEGHIJOSUWYaceghijosuwy",
        to: "ÂĈÊĜĤÎĴÔŜÛŴŶâĉêĝĥîĵôŝûŵŷ"
    },
    "_\"": {
        from: "AUau",
        to: "ǞǕǟǖ"
    },
    "_,": {
        from: "Oo",
        to: "Ǭǭ"
    },
    "_.": {
        from: "Aa",
        to: "Ǡǡ"
    },
    "_": {
        from: "AEIOU_aeiou",
        to: "ĀĒĪŌŪ¯āēīōū"
    },
    "`\"": {
        from: "Uu",
        to: "Ǜǜ"
    },
    "`": {
        from: "AEIOUaeiou",
        to: "ÀÈÌÒÙàèìòù"
    },
    "a": {
        from: "ben",
        to: "↔æ∠"
    },
    "b": {
        from: "()+-0123456789=bknpqru",
        to: "₍₎₊₋₀₁₂₃₄₅₆₇₈₉₌♝♚♞♟♛♜•"
    },
    "c": {
        from: "$Oagu",
        to: "¢©∩≅∪"
    },
    "dv": {
        from: "z",
        to: "ǆ"
    },
    "d": {
        from: "-adegz",
        to: "ð↓‡°†ʣ"
    },
    "e": {
        from: "$lmns",
        to: "€⋯—–∅"
    },
    "f": {
        from: "a",
        to: "∀"
    },
    "g": {
        from: "$-r",
        to: "¤ǥ∇"
    },
    "h": {
        from: "-v",
        to: "ℏƕ"
    },
    "i": {
        from: "-bfjps",
        to: "ɨ⊆∞ĳ⊇∫"
    },
    "l": {
        from: "\"$&\'-jz|",
        to: "“£∧‘łǉ⋄∨"
    },
    "m": {
        from: "iou",
        to: "µ∈×"
    },
    "n": {
        from: "jo",
        to: "ǌ¬"
    },
    "o": {
        from: "AOUaeiu",
        to: "Å⊚Ůåœƣů"
    },
    "p": {
        from: "Odgrt",
        to: "℗∂¶∏∝"
    },
    "r": {
        from: "\"\'O",
        to: "”’®"
    },
    "s": {
        from: "()+-0123456789=abnoprstu",
        to: "⁽⁾⁺⁻⁰ⁱ⁲⁳⁴⁵⁶⁷⁸⁹⁼ª⊂ⁿº⊃√ß∍∑"
    },
    "t": {
        from: "-efmsu",
        to: "ŧ∃∴™ς⊢"
    },
    "u": {
        from: "-AEGIOUaegiou",
        to: "ʉĂĔĞĬŎŬ↑ĕğĭŏŭ"
    },
    "v\"": {
        from: "Uu",
        to: "Ǚǚ"
    },
    "v": {
        from: "ACDEGIKLNORSTUZacdegijklnorstuz",
        to: "ǍČĎĚǦǏǨĽŇǑŘŠŤǓŽǎčďěǧǐǰǩľňǒřšťǔž"
    },
    "w": {
        from: "bknpqr",
        to: "♗♔♘♙♕♖"
    },
    "x": {
        from: "O",
        to: "⊗"
    },
    "y": {
        from: "$",
        to: "¥"
    },
    "z": {
        from: "-",
        to: "ƶ"
    },
    "|": {
        from: "Pp|",
        to: "Þþ¦"
    },
    "~!": {
        from: "=",
        to: "≆"
    },
    "~": {
        from: "-=AINOUainou~",
        to: "≃≅ÃĨÑÕŨãĩñõũ≈"
    },
};